Repository Ainraven/iv1201, pull requests merged in 2025-03, with the labels that each got.

#7 feat(database): add findApplicationByApplicationID & some minor refactoring
  integration/ApplicationDAO.js
  integration/UserDAO.js
  package.json
  tests/applicationDAO.test.js
  tests/userDAO.test.js
Labels: A-backend, P-medium, C-database, C-styling

#9 Authentication fullstack
  api/index.ejs
  api/public/css/loginStyle.css
  api/public/css/style.css
  api/public/js/loginScript.js
  api/public/js/script.js
  api/views/index.ejs
  api/views/loginView.ejs
  controller/controller.js
  integration/ApplicationDAO.js
  integration/UserDAO.js
  model/person.js
  package-lock.json
  package.json
  routes/auth.js
  server.js
  tests/databaseTest.js
  tests/userDAO.test.js
Labels: P-high, T-feature, A-everything

#10 Documentation
  README.md
  architectural-decisions.md
  database.md
Labels: P-low, T-docs, A-everything

#11 Applications UI
  api/public/js/applicationsScript.js
  api/public/js/script.js
  api/views/applicationsView.ejs
  api/views/index.ejs
  controller/controller.js
  integration/ApplicationDAO.js
  integration/UserDAO.js
  server.js
Labels: A-backend, P-high, T-feature

#12 Create user UI
  api/public/css/create_user_style.css
  api/public/js/create_user_script.js
  api/views/create_user.ejs
  controller/controller.js
Labels: A-frontend, P-medium, T-feature

#13 Authorisation backend
  api/public/js/applicationsScript.js
  api/public/js/auth.js
  api/public/js/loginScript.js
  api/views/index.ejs
  controller/controller.js
  integration/UserDAO.js
  middleware/authorisationMiddle.js
  package-lock.json
  package.json
  routes/applicationsRoutes.js
  routes/authRoutes.js
  server.js
Labels: A-backend, P-high, T-feature

#14 Pages
  api/public/css/signupStyle.css
  api/public/js/applicationsScript.js
  api/public/js/loginScript.js
  api/public/js/signupScript.js
  api/views/signup.ejs
  controller/controller.js
  integration/UserDAO.js
  routes/authRoutes.js
  server.js
Labels: A-backend, P-high, T-feature, T-misc, C-styling

#17 Applications, errors and persistency
  api/public/css/applicationsStyle.css
  api/public/css/loginStyle.css
  api/public/css/style.css
  api/public/js/applicationsScript.js
  api/public/js/headerScript.js
  api/public/js/loginScript.js
  api/public/js/profileScript.js
  api/public/js/signupScript.js
  api/views/403.ejs
  api/views/404.ejs
  api/views/applicationsView.ejs
  api/views/loginView.ejs
  api/views/signupView.ejs
  controller/controller.js
  integration/ApplicationDAO.js
  server.js
Labels: P-high, T-bug, T-feature, A-everything

#20 Error tests
  api/public/js/applicationsScript.js
  api/public/js/loginScript.js
  api/public/js/profileScript.js
  api/public/js/script.js
  api/public/js/signupScript.js
  api/views/index.ejs
  controller/controller.js
Labels: A-frontend, P-high, T-feature
